# Conda package metadata for NEMO_Nowcast

package:
  name: plotsr
  version: "0.1"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy   >=1.21
    - matplotlib  >=3.3
    - pandas  >=1.2.4

about:
  home: https://github.com/schneebergerlab/plotsr
  license: MIT License
  license_file: LICENSE
  summary: Package to plot structural annotations between multiple genomes

extra:
  maintainers:
    - Manish Goel <goel@mpipz.mpg.de>
